name: Deployment

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build_push_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Docker login to ghcr.io
        run: docker login ghcr.io -u deanomus -p ${{ secrets.GHCR_KEY }}

      - name: Build and tag image
        run: docker build -t ghcr.io/deanomus/mkcert-docker/mkcert-docker:latest -t ghcr.io/deanomus/mkcert-docker/mkcert-docker:build-${{ github.run_number }} -f ./Dockerfile .

      - name: Push latest image
        run: docker push ghcr.io/deanomus/mkcert-docker/mkcert-docker:latest

      - name: Push build-${{ github.run_number }} image
        run: docker push ghcr.io/deanomus/mkcert-docker/mkcert-docker:build-${{ github.run_number }}